version: '3.3'
services:

  notebook:
    image: hammer/jupyter:latest
    command: "/usr/local/bin/start.sh jupyter lab --NotebookApp.token=''"
    volumes:
      - work:/home/jovyan/work
    ports:
      - 18888:8888

volumes:
  work:
  
